services:
  mcp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp
    ports:
        - 8765:8765
    networks:
        - otobo_default
    environment:
        - OTOBO_MCP_INTERNAL_URL=http://web:5000
        - OTOBO_MCP_PUBLIC_URL=https://localhost/otobo/index.pl
        - OTOBO_MCP_WEBSERVICE=OTOBO-AI
        - OTOBO_MCP_SSL_VERIFY=false
        - OTOBO_MCP_TIMEOUT=30
        - OTOBO_MCP_TRANSPORT=streamable-http
        - OTOBO_MCP_BIND=0.0.0.0
        - OTOBO_MCP_PORT=8765
        - OTOBO_MCP_LOGLEVEL=10
        # see https://docs.python.org/3/library/logging.html#logging-levels
        # for loglevel description
        - OTOBO_MCP_ENABLED_TOOLS=faq_fulltext_search,get_link_to_faq,get_ticket_details,ticket_fulltext_search,unlink_ticket_to_ticket,find_similar_tickets,get_link_to_ticket,link_ticket_to_ticket,transfer_ticket_to_destination_queue,update_generated_response


networks:
  otobo_default:
    external: true

